name: flutter_string_encryption
description: Cross-platform string encryption using common best-practices.
version: 0.3.2
author: Alexander Golovnya <alex@allsports.by>
homepage: https://github.com/allsportsby/flutter_string_encryption

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.github.sroddy.flutterstringencryption
        pluginClass: FlutterStringEncryptionPlugin
      ios:
        pluginClass: FlutterStringEncryptionPlugin
